# Generated by Django 2.1.1 on 2019-07-06 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190706_1141'),
        ('user', '0005_usermodelpermission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermodelpermission',
            unique_together={('user', 'model', 'permission')},
        ),
    ]
