# Generated by Django 2.1.1 on 2019-07-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190706_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodelpermission',
            name='allow',
            field=models.BooleanField(default=True),
        ),
    ]
