# Generated by Django 2.1.1 on 2019-07-07 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_issuedetails'),
        ('user', '0007_usermodelpermission_allow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRole',
            new_name='UserRoleDepartment',
        ),
    ]
