# Generated by Django 2.1.1 on 2019-07-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190707_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cellphone',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
