# Generated by Django 2.1.1 on 2019-06-29 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_invitation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='role',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='core.Role'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='name',
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('email', 'department')},
        ),
    ]
