# Generated by Django 2.1.1 on 2019-07-06 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190629_1610'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departmentrolemodelpermission',
            unique_together={('department', 'role', 'model', 'permission')},
        ),
    ]
