# Generated by Django 2.1.1 on 2019-07-08 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_issuedetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IssueDetails',
        ),
        migrations.DeleteModel(
            name='TaskIssueResulation',
        ),
    ]
