# Generated by Django 2.1.1 on 2019-07-09 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_issuedetails_taskissueresulation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departmentmodelpermission',
            unique_together={('department', 'model', 'permission')},
        ),
    ]
