# Generated by Django 2.1.1 on 2019-06-30 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190629_1610'),
        ('user', '0005_usermodelpermission'),
        ('project', '0003_auto_20190628_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedetail',
            name='task',
        ),
        migrations.AddField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='issue_assigned', to='user.User'),
        ),
        migrations.AddField(
            model_name='issue',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='issuedetail',
            name='issue',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.Issue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuedetail',
            name='updated_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='user.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskdetail',
            name='updated_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='user.User'),
            preserve_default=False,
        ),
    ]
